<a href="https://colab.research.google.com/github/rabbi123080/An-Effective-Diabetes-Prediction-System-Using-Machine-Learning-Techniques/blob/main/Diabetes_ICAICT_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeCV, LassoCV, Ridge, Lasso

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
import io
df = pd.read_csv(io.BytesIO(uploaded['diabetes.csv']))
df.head(5)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
X = df.drop('Outcome', axis = 1)
y = df['Outcome']

In [ ]:
df['Glucose'] = df['Glucose'].replace(to_replace = 0, value =np.NaN)
df['BloodPressure'] = df['BloodPressure'].replace(to_replace = 0, value =np.NaN)
df['SkinThickness'] = df['SkinThickness'].replace(to_replace = 0, value =np.NaN)
df['Insulin'] = df['Insulin'].replace(to_replace = 0, value =np.NaN)
df['BMI'] = df['BMI'].replace(to_replace = 0, value =np.NaN)

In [ ]:
df.isnull().sum()/len(df)*100

Pregnancies                  0.000000
Glucose                      0.651042
BloodPressure                4.557292
SkinThickness               29.557292
Insulin                     48.697917
BMI                          1.432292
DiabetesPedigreeFunction     0.000000
Age                          0.000000
Outcome                      0.000000
dtype: float64

In [ ]:
a = df.isnull().sum()/len(df)*100
# saving column names in a variable
variables = df.columns
variable = [ ]
for i in range(0,9):
    if a[i]<=20:   #setting the threshold as 20%
        variable.append(variables[i])

In [ ]:
variable

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Outcome']

In [ ]:
df = df[variable]

In [ ]:
df.corr()

Pregnancies   Glucose  ...       Age   Outcome
Pregnancies                  1.000000  0.128135  ...  0.544341  0.221898
Glucose                      0.128135  1.000000  ...  0.267136  0.494650
BloodPressure                0.214178  0.223192  ...  0.330107  0.170589
BMI                          0.021719  0.232771  ...  0.025841  0.313680
DiabetesPedigreeFunction    -0.033523  0.137246  ...  0.033561  0.173844
Age                          0.544341  0.267136  ...  1.000000  0.238356
Outcome                      0.221898  0.494650  ...  0.238356  1.000000

[7 rows x 7 columns]

In [ ]:
df = df.drop('Age', axis = 1)

In [ ]:
df.isnull().sum()/len(df)*100

Pregnancies                 0.000000
Glucose                     0.651042
BloodPressure               4.557292
BMI                         1.432292
DiabetesPedigreeFunction    0.000000
Outcome                     0.000000
dtype: float64

In [ ]:
df.dropna(inplace=True)
df

Pregnancies  Glucose  ...  DiabetesPedigreeFunction  Outcome
0              6    148.0  ...                     0.627        1
1              1     85.0  ...                     0.351        0
2              8    183.0  ...                     0.672        1
3              1     89.0  ...                     0.167        0
4              0    137.0  ...                     2.288        1
..           ...      ...  ...                       ...      ...
763           10    101.0  ...                     0.171        0
764            2    122.0  ...                     0.340        0
765            5    121.0  ...                     0.245        0
766            1    126.0  ...                     0.349        1
767            1     93.0  ...                     0.315        0

[724 rows x 6 columns]

In [ ]:
X = df.drop('Outcome', axis = 1)
#X = df[['Pregnancies','Glucose', 'SkinThickness','Insulin','BMI','Age']]
y = df['Outcome']

In [ ]:
X.fillna(X.mean(), inplace=True)
X

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6    148.0           72.0  ...  33.6                     0.627   50
1              1     85.0           66.0  ...  26.6                     0.351   31
2              8    183.0           64.0  ...  23.3                     0.672   32
3              1     89.0           66.0  ...  28.1                     0.167   21
4              0    137.0           40.0  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10    101.0           76.0  ...  32.9                     0.171   63
764            2    122.0           70.0  ...  36.8                     0.340   27
765            5    121.0           72.0  ...  26.2                     0.245   30
766            1    126.0           60.0  ...  30.1                     0.349   47
767            1     93.0           70.0  ...  30.4                     0.315   23

[768 rows x 8 columns]

In [ ]:
from sklearn.impute import SimpleImputer
my_imputer = SimpleImputer()
X = my_imputer.fit_transform(X)

In [ ]:
X = pd.DataFrame(X)
X

0      1     2     3      4
0     6.0  148.0  72.0  33.6  0.627
1     1.0   85.0  66.0  26.6  0.351
2     8.0  183.0  64.0  23.3  0.672
3     1.0   89.0  66.0  28.1  0.167
4     0.0  137.0  40.0  43.1  2.288
..    ...    ...   ...   ...    ...
763  10.0  101.0  76.0  32.9  0.171
764   2.0  122.0  70.0  36.8  0.340
765   5.0  121.0  72.0  26.2  0.245
766   1.0  126.0  60.0  30.1  0.349
767   1.0   93.0  70.0  30.4  0.315

[768 rows x 5 columns]

In [ ]:
from collections import Counter
from imblearn.over_sampling import SMOTE
counter = Counter(y)
print(counter)

Counter({0: 500, 1: 268})


/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
from imblearn.over_sampling import RandomOverSampler
over = RandomOverSampler()
X, y = over.fit_resample(X, y)
counter = Counter(y)
print(counter)

Counter({1: 500, 0: 500})


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

In [ ]:
X_train = pd.DataFrame(X_train)

In [ ]:

# import the required functions and object.
from sklearn.feature_selection import mutual_info_classif
from sklearn.feature_selection import SelectKBest

# select the number of features you want to retain.
select_k = 7

# get only the numerical features.
numerical_x_train = X_train[X_train.select_dtypes([np.number]).columns]


# create the SelectKBest with the mutual info strategy.
selection = SelectKBest(mutual_info_classif, k=select_k).fit(numerical_x_train, y_train)

# display the retained features.
features = X_train.columns[selection.get_support()]
print(features)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'Age'],
      dtype='object')


In [ ]:
# Feature Scaling
from sklearn.preprocessing import RobustScaler

sc_X = RobustScaler()
X_train = sc_X.fit_transform(X_train)

# We are only using the transform and not the fit transform because we already fit the model
X_test = sc_X.transform(X_test)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
rfc = MLPClassifier()

rfc.fit(X_train, y_train)

rfc_pred = rfc.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, rfc_pred))
print(classification_report(y_test, rfc_pred))
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
accuracy = cross_val_score(rfc, X, y, cv = 10, scoring='accuracy')
print(accuracy)
print(accuracy.mean())
accuracy = cross_val_score(rfc, X, y, cv = 10, scoring='roc_auc')
print(accuracy)
print(accuracy.mean())
accuracy = cross_val_score(rfc, X, y, cv = 10, scoring='f1')
print(accuracy)
print(accuracy.mean())
accuracy = cross_val_score(rfc, X, y, cv = 10, scoring='precision')
print(accuracy)
print(accuracy.mean())
accuracy = cross_val_score(rfc, X, y, cv = 10, scoring='recall')
print(accuracy)
print(accuracy.mean())

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[[67 24]
 [13 96]]
              precision    recall  f1-score   support

           0       0.84      0.74      0.78        91
           1       0.80      0.88      0.84       109

    accuracy                           0.81       200
   macro avg       0.82      0.81      0.81       200
weighted avg       0.82      0.81      0.81       200

[0.59 0.71 0.67 0.61 0.75 0.75 0.72 0.7  0.66 0.69]
0.6849999999999999
[0.7128 0.8416 0.7604 0.6692 0.8604 0.7968 0.8476 0.8608 0.778  0.7896]
0.79172


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


[0.7047619  0.66666667 0.67924528 0.67857143 0.59459459 0.70103093
 0.66666667 0.76635514 0.68041237 0.76033058]
0.6898635561948514
[0.65957447 0.7037037  0.63636364 0.61403509 0.69354839 0.7
 0.7755102  0.76923077 0.6779661  0.67164179]
0.6901574149020612
[0.72 0.56 0.48 0.8  0.84 0.8  0.74 0.82 0.16 0.78]
0.67


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
parameters = {    
 'criterion':['gini','entropy'],
          'n_estimators': [100, 200, 50, 500],
          'max_leaf_nodes': [10, 30, 50, 100],
          'max_depth': [10, 50, 100]
 }

In [ ]:
grid=RandomizedSearchCV(rfc, parameters,  refit = True, verbose=3, cv=3, n_jobs=-1)

In [ ]:
grid.fit(X_train, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:   14.3s finished


RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [ ]:
grid.best_params_

{'criterion': 'entropy',
 'max_depth': 50,
 'max_leaf_nodes': 30,
 'n_estimators': 200}

In [ ]:
grid.best_estimator_

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=50, max_features='auto',
                       max_leaf_nodes=30, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
accuracy = cross_val_score(grid.best_estimator_, X, y, cv = 10, scoring='accuracy')
print(accuracy)
print(accuracy.mean())

[0.76 0.78 0.75 0.75 0.85 0.83 0.85 0.86 0.82 0.82]
0.807


In [ ]:
print(accuracy.mean())

0.8100000000000002
